### Create new User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdf@asdf.com",
  "password": "asdfsadf"
}


### Find a particular user with a given id
GET http://localhost:3000/auth/2


### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com


### Remove a particular user with a given id
DELETE http://localhost:3000/auth/8


### Update a particular user with a given id
PATCH http://localhost:3000/auth/8
Content-Type: application/json

{
  "password": "asdf"
}